feature: filter asset logs by asset types-#164827041
AndelaOSP/art-backend pull request #286
Opened 2019-04-25 13:53 UTC by kmazi

### What does this PR do?
Enables filtering asset logs by asset types

### Description of Task to be completed?
Add filtering by asset_type to assetlog queries

#### How should this be manually tested?
1. On browser, goto url reverse('asset-logs-list') and add query string/ parameter specifying the asset_type.

### Any background context you want to provide?
Formerly an admin user could only query for asset logs in their location without filtering by asset type

### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/164827041

2019-04-26 08:17 UTC, egichuri commented
@kmazi can we use [filters](https://github.com/AndelaOSP/art-backend/blob/develop/api/filters.py) for this?

2019-04-26 08:18 UTC, egichuri requested changes
@kmazi can we use [filters](https://github.com/AndelaOSP/art-backend/blob/develop/api/filters.py) for this?

2019-05-02 11:01 UTC, kmazi commented
@egichuri Please help check again

2019-05-02 16:19 UTC, egichuri approved these changes

2019-05-02 17:17 UTC, merged