Filter and Paginate assets assigned to a department
AndelaOSP/art-backend pull request #297
Opened 2019-05-17 07:30 UTC by kenneth051

#### What does this PR do?
Filter and Paginate assets assigned to a department

#### Description of Task to be completed?
Scenario: Filter and  Paginate department assets
Given an admin with access
When I request to view a long list of assets assigned to a department
Then I should be able to see them in a paginated format
Also on the assets endpoint filter assets by the department.
On the department's endpoint(all and 1), there should be a count on assets a department has

#### How should this be manually tested?
1. On postman, goto http://127.0.0.1:8000/api/v1/departments/<department id> and do a get request. you will see paginated assets assigned.
on the assets endpoint, you can also filter by department to see all assets assigned to departments.
 `http://127.0.0.1:8000/api/v1/assets?department=3`

#### Any background context you want to provide?
Ensure that you have assigned assets to that department first

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2146417/stories/165930402

2019-05-21 09:46 UTC, egichuri requested changes
@kenneth051 did you consider using filters? we have something similar for users [here](https://github.com/AndelaOSP/art-backend/blob/a22c1608c7eee2c67da74c4fccf53058efe2f510/api/filters.py#L46) and [here](https://github.com/AndelaOSP/art-backend/blob/a22c1608c7eee2c67da74c4fccf53058efe2f510/api/filters.py#L127)

2019-05-28 12:16 UTC, egichuri approved these changes

2019-05-28 12:42 UTC, kmazi requested changes

2019-05-28 12:42 UTC, kmazi commented on api/tests/test_asset_api.py
> +    def test_admin_can_filter_asset_by_asset_department(self, mock_verify_id_token):
Perhaps a more descriptive name would be `test_admin_can_filter_asset_by_assignee_department`

2019-05-28 12:42 UTC, kmazi commented on api/tests/test_asset_api.py
> +        )
Pretty comprehensive assertions. It's also important to assert the number of asset expected after filtering.

2019-05-28 15:46 UTC, kmazi approved these changes

2019-05-28 15:47 UTC, merged