ft(workspace): office workspace
AndelaOSP/art-backend pull request #314
Opened 2019-07-03 21:09 UTC by Eyansky

- Admin can view assets in a given workspace

[Finishes #166575309]

#### What does this PR do?
- Admin can view assets in a given workspace

#### Description of Task to be completed?
Scenario: assets assigned to a workspace
Given an admin with access
When I request to view assets in a given workspaces
Then I should see a list of the assigned assets

#### How should this be manually tested?
1. On browser, goto url ...

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
[#166575309](https://www.pivotaltracker.com/story/show/166575309)

#### Postman Documentation

#### Screenshots (If applicable)

2019-07-10 10:23 UTC, raheemazeezabiodun commented on api/serializers/assets.py
> +        fields = ("uuid", "asset_category", "serial_number", "asset_code", "asset_type")
this should be a tuple

2019-07-10 13:05 UTC, Eyansky commented on api/serializers/assets.py
> +        fields = ("uuid", "asset_category", "serial_number", "asset_code", "asset_type")
It is a tuple

2019-08-23 12:50 UTC, kmazi requested changes

2019-08-23 12:50 UTC, kmazi commented on api/tests/test_office_workspace.py
> +    def est_can_get_workspacet(self, mock_verify_token):
All test methods should start with test_* for it to be discovered.

2019-08-28 21:00 UTC, closed without merging